"""P1-3: add Job.payment_reference (Quick Book payment ref)

Revision ID: 561ade83d396
Revises: 1f0459db6281
Create Date: 2026-06-27 22:28:07.649094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561ade83d396'
down_revision = '1f0459db6281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_job_payment_reference', ['payment_reference'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint('uq_job_payment_reference', type_='unique')
        batch_op.drop_column('payment_reference')

    # ### end Alembic commands ###
