"""F2/#7: MarketplaceService + MarketplaceServicePrice + Job pricing inputs

Revision ID: 9500378659f3
Revises: 3b39abc8521c
Create Date: 2026-07-01 05:59:08.957829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9500378659f3'
down_revision = '3b39abc8521c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_quick_bookable', sa.Boolean(), nullable=False),
    sa.Column('pricing_mode', sa.String(length=20), nullable=True),
    sa.Column('flat_price', sa.Float(), nullable=True),
    sa.Column('created_by_tenant_id', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('marketplace_service_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace_service_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_service_id'], ['marketplace_service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace_service_id', 'frequency', name='_mkt_service_frequency_uc')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketplace_service_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('frequency', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_job_marketplace_service_id', 'marketplace_service', ['marketplace_service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint('fk_job_marketplace_service_id', type_='foreignkey')
        batch_op.drop_column('frequency')
        batch_op.drop_column('marketplace_service_id')

    op.drop_table('marketplace_service_price')
    op.drop_table('marketplace_service')
    # ### end Alembic commands ###
