"""add QuoteRequest.marketplace_status

Revision ID: 9d2c9f06ab9f
Revises: 35f74904ead7
Create Date: 2026-06-25 23:01:24.036719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2c9f06ab9f'
down_revision = '35f74904ead7'
branch_labels = None
depends_on = None


def upgrade():
    # P0-2: introduce QuoteRequest.marketplace_status, replacing the
    # "tenant_id IS NULL == floating" overload.
    #
    # Sequence matters on a populated table: add the column NULLABLE first,
    # backfill every existing row, THEN enforce NOT NULL. Doing the NOT NULL
    # add in one shot (as autogenerate did) fails because existing rows have
    # no value. batch_alter_table is required for the ALTER on SQLite.

    # 1. Add as NULLABLE so existing rows do not violate the constraint.
    with op.batch_alter_table('quote_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketplace_status', sa.String(length=20), nullable=True))

    # 2. Backfill BEFORE the NOT NULL constraint is enforced:
    #    untenanted rows were the old "floating" leads; everything else is 'direct'.
    op.execute(
        "UPDATE quote_request "
        "SET marketplace_status = "
        "CASE WHEN tenant_id IS NULL THEN 'floating' ELSE 'direct' END"
    )

    # 3. Now that every row has a value, enforce NOT NULL.
    with op.batch_alter_table('quote_request', schema=None) as batch_op:
        batch_op.alter_column(
            'marketplace_status',
            existing_type=sa.String(length=20),
            nullable=False,
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_request', schema=None) as batch_op:
        batch_op.drop_column('marketplace_status')

    # ### end Alembic commands ###
