"""P1-4: add Job.created_at (timeout sweep age anchor)

Revision ID: c5cdba2db8d3
Revises: 561ade83d396
Create Date: 2026-06-28 14:26:42.205629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cdba2db8d3'
down_revision = '561ade83d396'
branch_labels = None
depends_on = None


def upgrade():
    # NOTE (manual): the column is NOT NULL but the table already has rows, so a
    # bare add_column would fail. Add it with a temporary server_default of now()
    # to backfill existing rows, then DROP the server_default so the column matches
    # the model (Python-side default=datetime.utcnow only — no permanent DB
    # default, no model/DB drift). New rows get their value from the ORM default.
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'created_at', sa.DateTime(),
            nullable=False, server_default=sa.text('now()')
        ))
        batch_op.alter_column('created_at', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
